version: "3"
services:
  app:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      REDIS_HOST: db
      REDIS_PORT: 6379
      ALLOWED_SHORTEN_ORIGINS: "https://discohook.org"
  db:
    image: redis:6.0-alpine
    command: redis-server --appendonly yes
    volumes:
      - "data:/data"
    restart: always
volumes:
  data:
