version: "3"
services:
  app:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      REDIS_ADDRESS: redis://db
      SHORTEN_ALLOWED_HOSTS: *
      SHORTEN_MAX_TTL: -1
  db:
    image: redis:6.0-alpine
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - "data:/data"
volumes:
  data:
